# Example configuration

get_bell_settings = false
do_drift_correction = false
do_error_estimation = 5 
do_accidental_correction = false
method = "MLE"

# You can define a starting matrix for the maximum likelihood estimation to improve your estimate
#starting_matrix = [[0.5, '0.5j'], ['0.5j', 0.5]]

## Minimizer specific arguments. You likely won't need to touch these
# ftol = 1e-8
# xtol = 1e-8
# gtol = 1e-8
# maxfev = 100 
# beta = 0.5 # beta to be used for hedged max likelihood (a.k.a. "add beta" rule or Lidstone's Law)
