name: Test

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      - run: uv sync --locked --all-extras --dev

      - run: uv run scripts/test
